### ISSUE TITLE
Stop ignoring lock files

### ISSUE THREAD

**Issue by kiliw** [hardforkio/bank-csv-to-ynab#19]
Currently we ignore lockfiles via the `.gitignore` like so:

https://github.com/hardforkio/bank-csv-to-ynab/blob/115d71c967d8c08bc4e4d52afae21661f267e836/.gitignore#L2

We have a `package-lock.json` in the codebase which must be committed and updated. So we should stop ignoring lockfiles on such a broad basis.

**Comment by kiliw** [comment]
The `package.lock.json` has to be tracked and commited. So the issue can be closed.

**Comment by kiliw** [comment]
I thought we stopped tracking the `package-lock.json` and since it is important for other users this should not be the case but I misunderstood the line in `.gitignore`. So we still track it. That's why the issue can be closed.

**Comment by Levino** [comment]
Your analysis is incorrect. Please read https://git-scm.com/docs/gitignore. Very interesting is the following:
> The purpose of gitignore files is to ensure that certain files not tracked by Git remain untracked.

**Comment by Levino** [comment]
There was as misunderstanding. The current pattern `.~lock*` does not include the `package-lock.json`. So we can leave the line in the `.gitignore` because we want potentially ignore the files tracked by this search pattern.
